name: Add YAML Front Matter

on:
  push:
    branches:
      - main  # 或者其他你想要部署的分支
  workflow_dispatch:

jobs:
  add-front-matter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PyYAML
      run: pip install pyyaml

    - name: Add YAML Front Matter
      run: |
        for file in $(find . -name "*.md"); do
          if ! grep -q '---' "$file"; then
            echo -e "---\nlayout: post\ntitle: \"$(basename "$file" .md)\"\ndate: $(date +%Y-%m-%d)\n---\n$(cat "$file")" > "$file"
          fi
        done

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Add YAML front matter to Markdown files'
        git push
