name: Add YAML Front Matter

# 触发条件：推送到主分支或手动触发
on:
  push:
    branches:
      - main
  workflow_dispatch:

# 明确定义所需权限
permissions:
  contents: write    # 允许修改仓库内容
  pull-requests: write    # 允许创建 PR（如果需要）

jobs:
  add-front-matter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # 使用最新版本
      with:
        fetch-depth: 1
        # 使用 fine-grained PAT 或 GITHUB_TOKEN
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Add YAML Front Matter
      run: |
        #!/bin/bash
        
        # 设置时间为 UTC
        export TZ=UTC
        
        for file in $(find . -name "*.md" -not -path "./.git/*" -not -path "./.github/*"); do
          # 跳过已经有前置数据的文件
          if ! grep -q '^---$' "$file"; then
            # 获取文件名（不包括扩展名）作为标题
            title=$(basename "$file" .md)
            # 获取文件的最后修改时间作为日期
            date=$(git log -1 --format="%aI" -- "$file" 2>/dev/null || date -u +"%Y-%m-%d")
            
            # 创建临时文件
            temp_file=$(mktemp)
            
            # 写入前置数据和原始内容
            {
              echo "---"
              echo "layout: post"
              echo "title: \"$title\""
              echo "date: $date"
              echo "author: Protomyst"
              echo "---"
              echo
              cat "$file"
            } > "$temp_file"
            
            # 替换原文件
            mv "$temp_file" "$file"
          fi
        done

    - name: Commit changes
      run: |
        if [[ -n $(git status -s) ]]; then
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'chore: Add YAML front matter to Markdown files [skip ci]'
          git push
        else
          echo "No changes to commit"
        fi
