name: Deploy Hugo site to Pages

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # Run at 2 AM UTC daily
  workflow_dispatch:      # Manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Download PaperMod theme
        run: |
          mkdir -p themes
          git clone https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod

      - name: Generate Front Matter and Process Files
        run: |
          # Create content directories if they don't exist
          mkdir -p content

          # Function to generate front matter
          generate_front_matter() {
            local file="$1"
            local title=$(basename "$file" .md)
            local date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            local category=$(dirname "$file" | sed 's|^./||')
            
            # Skip if front matter exists
            if grep -q "^---" "$file"; then
              cp "$file" "content/$category/$title.md"
              return
            fi
            
            # Generate new front matter
            {
              echo "---"
              echo "title: \"$title\""
              echo "date: $date"
              echo "categories: [\"$category\"]"
              echo "---"
              cat "$file"
            } > "content/$category/$title.md"
          }

          # Process all .md files except README.md
          find . -type f -name "*.md" ! -name "README.md" | while read file; do
            dir=$(dirname "$file" | sed 's|^./||')
            mkdir -p "content/$dir"
            generate_front_matter "$file"
          done

      - name: Configure Hugo
        run: |
          cat > config.toml << EOL
          baseURL = "https://doc.protomyst.com"
          languageCode = "en-us"
          title = "My Blog"
          theme = "PaperMod"
          
          [params]
            defaultTheme = "auto"
            ShowReadingTime = true
            ShowShareButtons = true
            ShowPostNavLinks = true
            ShowBreadCrumbs = true
            ShowCodeCopyButtons = true
            ShowToc = true
            
          [menu]
            main = [
              {identifier = "archives", name = "Archives", url = "/archives/", weight = 10},
              {identifier = "categories", name = "Categories", url = "/categories/", weight = 20}
            ]
          EOL

      - name: Build site
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4