name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 2 * * *'  # Runs at 2 AM UTC daily
  workflow_dispatch:      # Manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
          
      - name: Create Hugo site
        run: |
          # Initialize Hugo site
          hugo new site . --force
          
          # Install PaperMod theme
          git submodule add --force https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod
          
          # Create Hugo config
          cat > config.yml << 'EOL'
          baseURL: "/"
          title: "My Blog"
          theme: "PaperMod"
          
          menu:
            main:
              - identifier: archives
                name: Archives
                url: /archives/
                weight: 10
                
          params:
            defaultTheme: auto
            ShowReadingTime: true
            ShowShareButtons: true
            ShowPostNavLinks: true
            ShowBreadCrumbs: true
            ShowCodeCopyButtons: true
            ShowArchiveCount: true
          EOL
          
      - name: Process Markdown files
        run: |
          mkdir -p content/posts
          
          # Function to add front matter
          add_front_matter() {
            local file="$1"
            local folder="$2"
            local title=$(basename "$file" .md)
            local date=$(date +"%Y-%m-%d")
            
            # Don't process README.md
            if [ "$(basename "$file")" = "README.md" ]; then
              return
            }
            
            # Create temporary file
            temp_file=$(mktemp)
            
            # Add front matter
            cat > "$temp_file" << EOL
          ---
          title: "${title}"
          date: ${date}
          categories: ["${folder}"]
          tags: ["${folder}"]
          ---
          EOL
            
            # Append original content
            cat "$file" >> "$temp_file"
            
            # Copy to content/posts with folder prefix to maintain unique names
            cp "$temp_file" "content/posts/${folder}-${title}.md"
            rm "$temp_file"
          }
          
          # Process all .md files in subdirectories
          find . -type f -name "*.md" | while read -r file; do
            if [ "$(basename "$file")" != "README.md" ]; then
              folder=$(basename "$(dirname "$file")")
              add_front_matter "$file" "$folder"
            fi
          done
          
      - name: Build
        run: hugo --minify
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4