name: Deploy Hugo site to Pages

on:
  # 在推送到 main 分支时触发
  push:
    branches: ["main"]
  # 每天 2 点定时触发（UTC 时间 2:00，如需北京时间 2:00 则要改成 cron: "0 18 * * *"）
  schedule:
    - cron: "0 2 * * *"
  # 允许手动触发
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.121.1
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # 获取完整的 git 历史用于最后修改时间
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Init Hugo Site
        run: |
          # 创建 Hugo 站点配置
          cat > config.toml <<EOL
          baseURL = 'https://protomyst.github.io/Articles/'
          languageCode = 'zh-cn'
          title = 'Articles'
          theme = 'paper'
          
          # 下面的参数仅作示例，需要在主题里自行实现或适配搜索 / 归档
          [params]
            github = 'Protomyst'
            rss = true
            # 你可以在主题中使用这些开关来控制“搜索”和“归档”按钮的显示
            showSearch = true
            showArchive = true

          [taxonomies]
            category = 'categories'
            tag = 'tags'
            # 如果想单独设置 folder 作为自定义分类，则可在此添加
            # folder = 'folders'

          [markup.goldmark.renderer]
            unsafe = true

          # 示例：在主菜单添加“搜索”和“归档”按钮
          [menu]
            [[menu.main]]
              identifier = "archive"
              name = "归档"
              url = "/archives"
              weight = 1

            [[menu.main]]
              identifier = "search"
              name = "搜索"
              url = "/search"
              weight = 2
          EOL
          
          # 下载并设置主题
          git clone https://github.com/nanxiaobei/hugo-paper themes/paper
          
          # 创建 archetypes 模板
          mkdir -p archetypes
          cat > archetypes/default.md <<EOL
          ---
          title: "{{ replace .Name "-" " " | title }}"
          date: {{ .Date }}
          categories: []
          tags: []
          draft: false
          ---
          EOL
          
          # 创建内容目录
          mkdir -p content/posts

          # 移动除 README.md 之外的所有 markdown 文件到 content/posts
          find . -type f -iname "*.md" \
            ! -iname "README.md" \
            -not -path "./themes/*" \
            -not -path "./archetypes/*" \
            -not -path "./content/*" \
            -exec mv {} content/posts/ \;

          # 修正 front matter，并按文件夹名称创建归档（示例：将文件夹名加入到 categories 中）
          for file in content/posts/*.md; do
            if [ -f "$file" ]; then
              # 获取相对路径和所在文件夹作为分类
              dir_name=$(dirname "$file")
              # dir_name 通常是 content/posts/xxx ... 取最后一段 xxx
              folder=$(basename "$dir_name")

              # 如果文件没有 front matter，添加它
              if ! grep -q "^---" "$file"; then
                title=$(basename "$file" .md)
                date=$(git log -1 --format=%aI -- "$file")
                temp_file=$(mktemp)

                echo "---" > "$temp_file"
                echo "title: \"$title\"" >> "$temp_file"
                echo "date: $date" >> "$temp_file"
                # 将所在文件夹作为分类之一
                echo "categories:" >> "$temp_file"
                echo "  - \"$folder\"" >> "$temp_file"
                echo "---" >> "$temp_file"

                cat "$file" >> "$temp_file"
                mv "$temp_file" "$file"
              else
                # 如果已存在 front matter，可在此对已有 front matter 做更复杂处理（略）
                # 如需在已有 front matter 中追加 categories，可自行在此追加
                :
              fi
            fi
          done

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: hugo --gc --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
