name: Deploy Hugo site to Pages

on:
  # 在推送到主分支时触发
  push:
    branches: ["main"]
  # 每天凌晨2点触发
  schedule:
    - cron: '0 18 * * *' # UTC时间18点，北京时间凌晨2点
  # 允许手动触发
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.121.1
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb          

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # 获取完整的 git 历史用于最后修改时间
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Init Hugo Site
        run: |
          # 创建 Hugo 站点配置
          cat > config.toml <<EOL
          baseURL = 'https://doc.protomyst.com/'
          languageCode = 'zh-cn'
          title = 'Articles'
          theme = 'paper'
          
          [params]
            github = 'Protomyst'
            rss = true
            # 启用搜索
            enableSearch = true
            # 主页显示搜索和归档按钮
            homeInfoParams = ["posts", "archives", "search"]

          [taxonomies]
            category = 'categories'
            tag = 'tags'
            # 增加归档
            archive = 'archives'
            
          [markup.goldmark.renderer]
            unsafe = true

          # 搜索配置 (fuse.js)
          [outputs]
            home = [ "HTML", "RSS", "JSON" ]
          EOL
          
          # 下载并设置主题
          git clone https://github.com/nanxiaobei/hugo-paper themes/paper
          
          # 创建 archetypes 模板
          mkdir -p archetypes
          cat > archetypes/default.md <<EOL
          ---
          title: "{{ replace .Name "-" " " | title }}"
          date: {{ .Date }}
          categories: []
          tags: []
          draft: false
          ---
          EOL
          
          cat > archetypes/archives.md <<EOL
          ---
          title: "Archives"
          layout: "archives"
          summary: "archives"
          ---
          EOL
          
          # 创建内容目录
          mkdir -p content/posts
          
          # 移动所有 markdown 文件到 content/posts
          find . -name "*.md" -not -path "./themes/*" -not -path "./archetypes/*" -not -path "./content/*" -not -name "README.md" -exec mv {} content/posts/ \;
          
          # 修正 front matter
          for file in content/posts/*.md; do
            if [ -f "$file" ]; then
              # 如果文件没有 front matter，添加它
              if ! grep -q "^---" "$file"; then
                title=$(basename "$file" .md)
                date=$(git log -1 --format=%aI -- "$file")
                folder=$(basename $(dirname "$file"))
                temp_file=$(mktemp)
                echo "---" > "$temp_file"
                echo "title: \"$title\"" >> "$temp_file"
                echo "date: $date" >> "$temp_file"
                # 将文件夹名称添加到 archives
                echo "archives: [\"$folder\"]" >> "$temp_file"
                echo "---" >> "$temp_file"
                cat "$file" >> "$temp_file"
                mv "$temp_file" "$file"
              fi
            fi
          done
          
          # 创建 archives 页面
          hugo new archives.md

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: hugo --gc --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
