name: Initialize Workflows

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

# 环境变量配置
env:
  WORKFLOWS_REPO: "Protomyst/Resources"
  BRANCH: "main"

jobs:
  check-first-run:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check if first run
        id: check
        run: |
          # 获取提交数量
          commit_count=$(git rev-list --count HEAD)
          # 检查是否存在其他工作流文件
          workflow_count=$(ls -1 .github/workflows/ 2>/dev/null | grep -v initialize-workflows.yml | wc -l)
          
          if [ "$commit_count" -le 1 ] || [ "$workflow_count" -eq 0 ]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"
          else
            echo "should_run=false" >> "$GITHUB_OUTPUT"
          fi

  initialize:
    needs: check-first-run
    if: needs.check-first-run.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup directories
        run: |
          mkdir -p .github/workflows

      - name: Download workflows
        run: |
          # 下载工作流文件
          for file in add-front-matter.yml configure-settings.yml deploy-to-pages.yml; do
            for i in {1..3}; do
              if curl -fsSL -o ".github/workflows/$file" \
                "https://raw.githubusercontent.com/${{ env.WORKFLOWS_REPO }}/${{ env.BRANCH }}/$file"; then
                echo "Successfully downloaded $file"
                break
              else
                echo "Failed to download $file, attempt $i of 3"
                if [ $i -eq 3 ]; then
                  echo "Error: Failed to download $file after 3 attempts"
                  exit 1
                fi
                sleep 2
              fi
            done
          done

      - name: Verify downloads
        run: |
          # 检查文件完整性
          for file in add-front-matter.yml configure-settings.yml deploy-to-pages.yml; do
            if [ ! -f ".github/workflows/$file" ]; then
              echo "Error: $file is missing"
              exit 1
            fi
            
            if [ ! -s ".github/workflows/$file" ]; then
              echo "Error: $file is empty"
              exit 1
            fi
            
            # 验证YAML格式
            if ! yq eval ".github/workflows/$file" > /dev/null 2>&1; then
              echo "Error: $file is not valid YAML"
              exit 1
            fi
          done

      - name: Configure git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit changes
        run: |
          # 同步远程更改
          git fetch origin ${{ github.ref }}
          git switch -c temp-branch
          
          # 添加新文件
          git add .github/workflows/*.yml
          
          # 检查是否有更改需要提交
          if ! git diff --cached --quiet; then
            # 提交工作流文件
            git commit -m "chore: initialize workflow files"
            
            # 删除初始化工作流
            git rm -f .github/workflows/initialize-workflows.yml
            git commit -m "chore: remove initialization workflow"
            
            # 切换回主分支并合并更改
            git switch ${GITHUB_REF##*/}
            git merge temp-branch
            
            # 推送更改
            for i in {1..3}; do
              if git push origin ${GITHUB_REF##*/}; then
                echo "Successfully pushed changes"
                break
              else
                echo "Push failed, attempt $i of 3"
                git pull --rebase origin ${GITHUB_REF##*/}
                if [ $i -eq 3 ]; then
                  echo "Error: Failed to push changes after 3 attempts"
                  exit 1
                fi
                sleep 2
              fi
            done
          else
            echo "No changes to commit"
          fi

      - name: Cleanup
        if: always()
        run: |
          # 清理临时分支和文件
          git switch ${GITHUB_REF##*/}
          git branch -D temp-branch || true
          rm -f .github/workflows/initialize-workflows.yml
